kind: pipeline
type: exec
name: Build all Hosts

platform:
  os: linux
  arch: amd64

steps:
- name: Build Tower
  commands:
  - nix-build --config machines/rocky.nix
    #- name: Build Laptop
    #commands:
    #- nix-build machines/smoothie.nix

---

kind: pipeline
type: docker
name: Notify IRC

steps:
- name: Send notification
  image: plugins/irc
  settings:
    template: "[{{build.status}}]: {{build.message}} | #{{truncate build.commit 8}} {{build.event}} on {{repo.owner}}/{{repo.name}}/{{build.branch}} by {{build.author}} - {{build.link}}"
    nick: drone-bot
    channel: "#lounge-rocks"
    host: chat.freenode.net
    port: 6667
  when:
    branch:
    - main
    event:
    - push
    - cron
