{ config, pkgs, lib, ... }: {

    programs.home-manager.enable = true;

    xsession = {
      enable = true;
      # script gets generated by nixos
      scriptPath = ".hm-xsession";
      windowManager.i3 = {
        enable = true;
        package = pkgs.i3-gaps;
        # disable generation of default config
        config = null;
        # use config from file
        extraConfig =
          lib.strings.fileContents ./dotfiles/wm/i3.config;
      };
    };

    home.packages = with pkgs; [
      nerdfonts corefonts
      fd ripgrep
    ];

    # allow installation of fonts
    fonts.fontconfig.enable = true;

    manual.manpages.enable = true;

    # User programs configuration
    programs = {
      git = {
        enable = true;
        userEmail = "fbreuer@pm.me";
        userName = "Felix Breuer";
      };

      fish = {
        enable = true;
        shellAliases = { bla = "echo"; };
        promptInit = ''
          set fish_greeting
        '';
      };

      autojump = {
        enable = true;
        enableFishIntegration = true;
      };

      htop = {
        enable = true;
        treeView = true;
      };

      alacritty = { enable = true; };

      tmux = {
        enable = true;
        plugins = with pkgs; [ tmuxPlugins.gruvbox ];
        extraConfig =
          lib.strings.fileContents ./dotfiles/shell/.tmux.conf;
      };

      fzf = {
        enable = true;
        enableFishIntegration = true;
        defaultCommand = "fd --type f --hidden";
        fileWidgetCommand = "fd --type f --hidden";
        #defaultOptions = [
        #"--hidden"
        #"--follow"
        #"--exclude .git"
        #"--exclude .vim"
        #];
      };

      neovim = {
        enable = true;
        withNodeJs = true;
        withPython = true;
        withPython3 = true;
        withRuby = true;
        configure = {
          customRC = lib.strings.fileContents ./dotfiles/shell/.vimrc;
        };

        #extraConfig = lib.strings.fileContents ~/dotfiles/shell/.vimrc;
        #plugins = with pkgs.vimPlugins; [ vim-plug ];
      };

      firefox = {
        enable = true;
        #package = pkgs.firefox-bin;
      };
    };
}
