{ config, pkgs, lib, ... }:

{
  imports = [ <home-manager/nixos> ];

  security.sudo.wheelNeedsPassword = false;
  users.defaultUserShell = pkgs.fish;
  users.users.felix = {
    isNormalUser = true;
    home = "/home/felix";
    description = "Felix Breuer";
    extraGroups = [ "wheel" "networkmanager" "audio" "dialout" ]; # libvirtd
  };

  home-manager = {
    useUserPackages = true;
    useGlobalPkgs = true;
  };

  home-manager.users.felix = {
    programs.home-manager.enable = true;

    xsession = {
      enable = true;
      # script gets generated by nixos
      scriptPath = ".hm-xsession";
      windowManager.i3 = {
        enable = true;
        package = pkgs.i3-gaps;
        # disable generation of default config
        config = null;
        # use config from file
        extraConfig =
          lib.strings.fileContents /home/felix/dotfiles/wm/i3.config;
      };
    };

    # allow proprietary packages
    #nixpkgs.config.allowUnfree = true;
    home.packages = with pkgs; [ nerdfonts corefonts fd ripgrep ];

    # allow installation of fonts
    fonts.fontconfig.enable = true;

    manual.manpages.enable = true;

    programs.fish = {
      enable = true;
      shellAliases = { bla = "echo"; };
      promptInit = ''
        set fish_greeting
      '';
    };

    programs.autojump = {
      enable = true;
      enableFishIntegration = true;
    };

    programs.htop = {
      enable = true;
      treeView = true;
    };

    programs.alacritty = { enable = true; };

    programs.tmux = {
      enable = true;
      plugins = with pkgs; [ tmuxPlugins.gruvbox ];
      extraConfig =
        lib.strings.fileContents /home/felix/dotfiles/shell/.tmux.conf;
    };

    programs.fzf = {
      enable = true;
      enableFishIntegration = true;
      defaultCommand = "fd --type f --hidden";
      fileWidgetCommand = "fd --type f --hidden";
      #defaultOptions = [
      #"--hidden"
      #"--follow"
      #"--exclude .git"
      #"--exclude .vim"
      #];
    };

    programs.neovim = {
      enable = true;
      withNodeJs = true;
      withPython = true;
      withPython3 = true;
      withRuby = true;
      configure = {
        customRC = lib.strings.fileContents /home/felix/dotfiles/shell/.vimrc;
      };

      #extraConfig = lib.strings.fileContents ~/dotfiles/shell/.vimrc;
      #plugins = with pkgs.vimPlugins; [ vim-plug ];
    };

    programs.firefox = {
      enable = true;
      #package = pkgs.firefox-bin;
    };
  };

  environment = {
    variables = {
      EDITOR = "vim";
      VISUAL = "vim";
    };

    shellAliases = {
      vi = "nvim";
      svi = "sudo vim";
      nr = "nixos-rebuild";
      ne = "sudo vim /etc/nixos/configuration.nix";
      ns = "sudo nixos-rebuild switch --upgrade";
      nb = "nixos-rebuild build";
      h = "home-manager";
      he = "nvim $HOME/.config/nixpkgs/home.nix";
      hs = "home-manager switch";
    };

    systemPackages = with pkgs; [ curl git vim ];
  };
}
