{ config, pkgs, lib, ... }: {
  xsession = {
    enable = true;
    # script gets generated by nixos
    scriptPath = ".hm-xsession";
    windowManager.i3 = {
      enable = true;
      package = pkgs.i3-gaps;
      # disable generation of default config
      config = null;
      extraConfig = lib.strings.fileContents ./i3.config;
    };
  };
}
